### ISSUE TITLE
Update speedrun challenge-base branch based on new version of scaffold-stark

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/speedrunstark#144]
## Issue Overview

Scaffold Stark has been updated into version 3 with a lot of new features. We want to make sure that speedrunstark is in sync with the Scaffold Stark version.

## Proposed Solutions or Ideas

- Update the base fork branch
- Resolve any breaking changes

**Comment by vickiddev** [comment]
can i work on this? @metalboyrick

**Comment by CollinsC1O** [comment]
@metalboyrick I will love to work on this. I'm ready to work

**Comment by MPSxDev** [comment]
Glad to have participated in the Speedrunstark, I would love to take on this issue as I know more or less how everything works. I am immediately available to start working on this when ODHack 8.0 starts.

**Comment by MPSxDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello, I am Manuel, a process engineer and web3 developer. I have participated in Starknet Bootcamps and am an Elite winner of Speedrunstark. I have a high capacity to solve problems. I am a member of the DojoCoding community.
I hope this issue is assigned to me. I am available to work immediately to achieve what is required in the shortest time possible.

### How I plan on tackling this issue
To address the requirements of the issue, I will:

1. Update the base fork branch of `speedrunstark` to align with the new version 3 of `scaffold-stark`.
2. Review the release notes and documentation of `scaffold-stark` version 3 to identify any new features and breaking changes.
3. Implement necessary modifications to the codebase of `speedrunstark` to resolve any breaking changes introduced by the update.
4. Test the updated branch to ensure compatibility and proper functionality with the new version.

**Comment by Buuh2511** [comment]
I'm ready for this, may i assigned

**Comment by gianalarcon** [comment]
all yours @Buuh2511 !
